rootProject.name = "OnlineEducation"
include(":service:service-edu")
include(":service:service-oss")
include(":common:server-base")
include(":common:common-utils")
include(":common:security")
include(":service:service-vod")
include(":service:service-cms")
include(":service:service-acl")
include(":service:service-msm")
include(":service:service-ucenter")
include(":service:service-order")
include(":service:service-statistics")
include(":canal-clientedu")
include(":infrastructure:gateway")
